version: "1.0"
project:
  name: bodywork-mlflow
  docker_image: bodyworkml/bodywork-core:2.1.7
  DAG: server
stages:
  server:
    executable_module_path: mlflow_server.py
    requirements:
      #- mlflow[extras]==1.16.0
      - mlflow[extras]==1.24.0
      #- psycopg2-binary==2.8.6
      - psycopg2-binary==2.9.3
    secrets:
      MLFLOW_S3_ENDPOINT_URL: mlflow-config
      MLFLOW_BACKEND_STORE_URI: mlflow-config
      MLFLOW_DEFAULT_ARTIFACT_ROOT: mlflow-config

      MLFLOW_SERVER_HOST: mlflow-config
      MLFLOW_SERVER_WORKER: mlflow-config
      MLFLOW_SERVER_PORT: mlflow-config

      AWS_ACCESS_KEY_ID: aws-credentials
      AWS_SECRET_ACCESS_KEY: aws-credentials
      AWS_DEFAULT_REGION: aws-credentials
    cpu_request: 0.1
    memory_request_mb: 250
    service:
      max_startup_time_seconds: 30
      replicas: 1
      port: 5000
      ingress: false
logging:
  log_level: DEBUG
