version: "1.0"
project:
  name: bodywork-mlflow
  docker_image: bodyworkml/bodywork-core:latest
  DAG: server
stages:
  server:
    executable_module_path: mlflow_server.py
    requirements:
      - mlflow[extras]==1.16.0
      - psycopg2-binary==2.8.6
    secrets:
      MLFLOW_BACKEND_STORE_URI: "http://20.86.213.228:80"
      MLFLOW_DEFAULT_ARTIFACT_ROOT: "mlflow_artefacts"
      AWS_ACCESS_KEY_ID: "ExCQEPIepyEosUKJ"
      AWS_SECRET_ACCESS_KEY: "rpk4l2tNH367LhjsP2ubWdKWpmwGHqPd"
      AWS_DEFAULT_REGION: "eu-south-1"
    cpu_request: 0.1
    memory_request_mb: 250
    service:
      max_startup_time_seconds: 30
      replicas: 1
      port: 5000
      ingress: false
logging:
  log_level: INFO
